#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

import argparse
import datetime

__docformat__ = "restructuredtext en"

def main():
    options = _parse_args()

    start = datetime.datetime.now()

    text = raw_input("Type as fast as you can and press enter:\n")

    end = datetime.datetime.now()

    diff = end-start

    chars = len(text)
    time = float(diff.seconds)
    speed = chars/time

    print "You typed {chars} in {seconds}. That is {speed} chars/second or {min} chars/minute.".format(
        chars = chars,
        seconds = time,
        speed = speed,
        min = speed * 60,
    )


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(usage="", description="")
    parser.add_argument('args', metavar='N', type=str, nargs='*',
                   help='Positional arguments.')
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument('--version', action='version', version='<the version>')

    return parser.parse_args()


if __name__ == "__main__":
    main()
