#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

import argparse
import datetime

__docformat__ = "restructuredtext en"

def main():
    options = _parse_args()

    print("When you are ready, press enter and type as fast as you can. When you are done, press enter again.")

    input()

    start = datetime.datetime.now()

    text = input("Type!\n")

    end = datetime.datetime.now()
    diff = end-start
    chars = len(text)
    time = diff.seconds

    try:
        speed = chars/time
    except ZeroDivisionError:
        print("That was too short, please type more than a second.")
    else:
        print("You typed {chars:n} chars in {seconds:n} seconds. That is {speed:.1f} chars/second or {min:.1f} chars/minute.".format(
            chars = chars,
            seconds = time,
            speed = speed,
            min = speed * 60,
        ))

def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(usage="", description="")
    parser.add_argument('args', metavar='N', type=str, nargs='*',
                   help='Positional arguments.')

    return parser.parse_args()

if __name__ == "__main__":
    main()
